# Generated by Django 2.2.5 on 2019-11-24 20:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Introduction', models.TextField(max_length=300)),
                ('notre_Histoire', models.TextField(max_length=800)),
                ('qui_Somme_Nous', models.TextField(max_length=300)),
                ('nos_Valeurs', models.TextField(max_length=300)),
                ('nos_Missions', models.TextField(max_length=300)),
                ('notre_Vision', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, srid=4326)),
                ('Cycle', models.CharField(choices=[('Primaire', 'Primaire'), ('College', 'College'), ('Lycee', 'Lycee'), ('Université', 'Université')], default='Not selected', max_length=200)),
                ('Type', models.CharField(choices=[('Public', 'Public'), ('Privé', 'Privé')], default='Not selected', max_length=200)),
                ('Adress', models.CharField(default='Taroudant', max_length=200)),
                ('Latitude', models.FloatField(default=30, max_length=8)),
                ('Longitude', models.FloatField(default=-8, max_length=8)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('link', models.URLField(blank=True, null=True)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
