# Generated by Django 2.2.5 on 2019-11-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Photos_dentreprise',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
