# Generated by Django 2.2.5 on 2019-11-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0002_about_photos_dentreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adress', models.TextField(null=True)),
                ('Phone', models.TextField(max_length=25)),
                ('Email', models.TextField(max_length=30)),
            ],
        ),
    ]
