# Generated by Django 2.2.5 on 2020-03-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Name', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=700)),
            ],
        ),
    ]
