# Generated by Django 2.2.5 on 2020-03-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Photos_ArrierePlan',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
