# Generated by Django 2.2.5 on 2020-03-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0005_about_photos_arriereplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='facebookPage',
            field=models.TextField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='instaProfile',
            field=models.TextField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedIn',
            field=models.TextField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='youtubeChannel',
            field=models.TextField(max_length=80, null=True),
        ),
    ]
