# Generated by Django 2.2.5 on 2020-03-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0006_auto_20200312_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Adress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Phone',
            field=models.TextField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='contact',
            name='facebookPage',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instaProfile',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedIn',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='youtubeChannel',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
    ]
