# Generated by Django 2.2.5 on 2020-03-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0007_auto_20200312_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Photo_Personel',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
