# Generated by Django 2.2.5 on 2020-03-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0008_about_photo_personel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='Cycle',
        ),
        migrations.AddField(
            model_name='projet',
            name='Description',
            field=models.CharField(default='Not selected', max_length=300),
        ),
    ]
