# Generated by Django 2.2.5 on 2020-03-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0010_auto_20200326_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='Adress',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='projet',
            name='Département',
            field=models.CharField(blank=True, default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='projet',
            name='Services',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='projet',
            name='Tel',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
    ]
