# Generated by Django 2.2.5 on 2020-03-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0011_auto_20200326_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='Description_si_disop',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
    ]
