# Generated by Django 2.2.5 on 2020-03-27 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0014_auto_20200327_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='link_à_supprimer',
            new_name='link',
        ),
    ]
