# Generated by Django 2.2.5 on 2020-03-31 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0015_auto_20200327_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=120)),
                ('Description', models.CharField(max_length=520)),
                ('Icon', models.CharField(max_length=50)),
            ],
        ),
    ]
