# Generated by Django 2.2.5 on 2020-03-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0017_auto_20200331_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
