# Generated by Django 2.2.5 on 2020-03-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0018_auto_20200331_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='link',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
