# Generated by Django 2.2.5 on 2020-04-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0019_auto_20200331_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
