# Generated by Django 2.2.5 on 2020-04-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0020_auto_20200401_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pied_de_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_1', models.TextField(blank=True, null=True)),
                ('contenu_1', models.TextField(blank=True, null=True)),
                ('section_2', models.TextField(blank=True, null=True)),
                ('contenu_2', models.TextField(blank=True, null=True)),
                ('section_3', models.TextField(blank=True, null=True)),
                ('contenu_3', models.TextField(blank=True, null=True)),
                ('facebookPage', models.TextField(blank=True, max_length=80, null=True)),
                ('instaProfile', models.TextField(blank=True, max_length=80, null=True)),
                ('linkedIn', models.TextField(blank=True, max_length=80, null=True)),
                ('youtubeChannel', models.TextField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
