# Generated by Django 2.2.5 on 2020-04-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0021_auto_20200403_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Whatsp', models.TextField(max_length=300)),
                ('demande_nom', models.TextField(max_length=800)),
                ('demande_email', models.TextField(max_length=800)),
                ('demande_message', models.TextField(max_length=800)),
                ('section_adress', models.TextField(blank=True, null=True)),
                ('contenu_adress', models.TextField(blank=True, null=True)),
                ('section_phone', models.TextField(blank=True, null=True)),
                ('contenu_phone', models.TextField(blank=True, null=True)),
                ('section_email', models.TextField(blank=True, null=True)),
                ('contenu_email', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
