# Generated by Django 2.2.5 on 2020-04-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0022_contact_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pied_de_page',
            name='contenu_3_ligne2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pied_de_page',
            name='facebookPage',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pied_de_page',
            name='instaProfile',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pied_de_page',
            name='linkedIn',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pied_de_page',
            name='youtubeChannel',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='Description',
            field=models.TextField(max_length=520),
        ),
    ]
