# Generated by Django 2.2.5 on 2020-04-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0023_auto_20200403_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_page',
            name='contenu_adress',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='contact_page',
            name='demande_email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact_page',
            name='demande_message',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact_page',
            name='demande_nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact_page',
            name='section_adress',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='contact_page',
            name='section_email',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='contact_page',
            name='section_phone',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
