# Generated by Django 2.2.5 on 2020-04-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0024_auto_20200403_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_page',
            name='Whatsp',
            field=models.CharField(max_length=200),
        ),
    ]
