# Generated by Django 2.2.5 on 2020-04-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0025_auto_20200403_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tete_de_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accueil', models.CharField(blank=True, max_length=80, null=True)),
                ('Contact', models.CharField(blank=True, max_length=80, null=True)),
                ('A_propos', models.CharField(blank=True, max_length=80, null=True)),
                ('Prestations', models.CharField(blank=True, max_length=80, null=True)),
                ('Actualite', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
