# Generated by Django 2.2.5 on 2020-04-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0026_tete_de_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accueil_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_phrase1', models.CharField(max_length=200)),
                ('video_titre', models.CharField(max_length=200)),
                ('video_phrase2', models.CharField(max_length=200)),
                ('Intro', models.CharField(max_length=200)),
                ('prestations_section', models.CharField(max_length=200)),
                ('actualite_section', models.CharField(max_length=200)),
            ],
        ),
    ]
