# Generated by Django 2.2.5 on 2020-04-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0027_accueil_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accueil_page',
            name='Intro',
            field=models.TextField(max_length=800),
        ),
    ]
