# Generated by Django 2.2.5 on 2020-04-03 21:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0028_auto_20200403_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestations_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=120)),
                ('Description', models.TextField(max_length=520)),
                ('Icon', models.CharField(default='fas fa-', max_length=50)),
                ('Titre', models.CharField(max_length=80)),
                ('Contenu', ckeditor_uploader.fields.RichTextUploadingField()),
                ('link', models.URLField(blank=True, null=True)),
                ('Photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
