# Generated by Django 2.2.5 on 2020-04-03 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0029_auto_20200403_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestations_page',
            name='Nom',
        ),
    ]
