# Generated by Django 2.2.5 on 2020-04-03 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0030_remove_prestations_page_nom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projet',
            new_name='Webmap',
        ),
    ]
