# Generated by Django 2.2.5 on 2020-04-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0031_auto_20200403_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Phrase_principale',
            field=models.TextField(default='Nous sommes des', max_length=300),
        ),
        migrations.AddField(
            model_name='about',
            name='mot_defilant_1',
            field=models.TextField(default='Topographes', max_length=300),
        ),
        migrations.AddField(
            model_name='about',
            name='mot_defilant_2',
            field=models.TextField(default='Géomaticiens', max_length=300),
        ),
        migrations.AddField(
            model_name='about',
            name='mot_defilant_3',
            field=models.TextField(default='Développeurs', max_length=300),
        ),
    ]
