# Generated by Django 2.2.5 on 2020-04-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0032_auto_20200403_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='mini_phrase',
            field=models.TextField(default='~Nos simples interets ~', max_length=300),
        ),
    ]
