# Generated by Django 2.2.5 on 2020-04-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0033_about_mini_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pied_de_page',
            name='section_1',
            field=models.TextField(blank=True, default='Qui somme nous?', null=True),
        ),
        migrations.AlterField(
            model_name='pied_de_page',
            name='section_2',
            field=models.TextField(blank=True, default='Ou nous trouver ?', null=True),
        ),
        migrations.AlterField(
            model_name='pied_de_page',
            name='section_3',
            field=models.TextField(blank=True, default='Nous contacter', null=True),
        ),
    ]
