# Generated by Django 2.2.5 on 2020-04-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0034_auto_20200404_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Phrase_principale',
            field=models.CharField(default='Nous sommes des', max_length=300),
        ),
        migrations.AlterField(
            model_name='about',
            name='mini_phrase',
            field=models.CharField(default='~Nos simples interets ~', max_length=300),
        ),
        migrations.AlterField(
            model_name='about',
            name='mot_defilant_1',
            field=models.CharField(default='Topographes', max_length=300),
        ),
        migrations.AlterField(
            model_name='about',
            name='mot_defilant_2',
            field=models.CharField(default='Géomaticiens', max_length=300),
        ),
        migrations.AlterField(
            model_name='about',
            name='mot_defilant_3',
            field=models.CharField(default='Développeurs', max_length=300),
        ),
    ]
