# Generated by Django 2.2.5 on 2020-04-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0035_auto_20200404_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Info_titre',
            field=models.CharField(default='A propos de Ste.Chetouani.', max_length=300),
        ),
    ]
