# Generated by Django 2.2.5 on 2020-04-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0037_auto_20200404_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pied_de_page',
            name='facebookPage',
            field=models.CharField(blank=True, default='https://www.facebook.com/chetopgeo/', max_length=80, null=True),
        ),
    ]
