# Generated by Django 2.2.5 on 2020-04-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0038_auto_20200404_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_page',
            name='Phrase_formulaire',
            field=models.CharField(default='Enovoyz-nous un message', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact_page',
            name='demande_email',
            field=models.CharField(default='votre email', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact_page',
            name='demande_message',
            field=models.CharField(default='tapez nous un message', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact_page',
            name='demande_nom',
            field=models.CharField(default='dites nous votre nom', max_length=200),
        ),
    ]
