# Generated by Django 2.2.5 on 2020-04-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0040_auto_20200404_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_page',
            name='section_adress',
            field=models.CharField(blank=True, default='Adress', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='contact_page',
            name='section_email',
            field=models.CharField(blank=True, default='Nous contacter', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='contact_page',
            name='section_phone',
            field=models.CharField(blank=True, default='Telephone', max_length=800, null=True),
        ),
    ]
