# Generated by Django 2.2.5 on 2020-04-12 18:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0043_auto_20200412_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='Photos_dentreprise',
        ),
        migrations.RemoveField(
            model_name='about',
            name='histoire',
        ),
        migrations.RemoveField(
            model_name='about',
            name='notre_Histoire',
        ),
        migrations.AlterField(
            model_name='about',
            name='nos_Missions',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='nos_Valeurs',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='notre_Vision',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='qui_Somme_Nous',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000),
        ),
    ]
