# Generated by Django 2.2.5 on 2020-04-12 18:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0045_about_titre_carte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Introduction',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='about',
            name='nos_Missions',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='about',
            name='nos_Valeurs',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='about',
            name='notre_Vision',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='about',
            name='qui_Somme_Nous',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=100000),
        ),
    ]
