# Generated by Django 2.2.5 on 2020-04-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0046_auto_20200412_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=120)),
                ('Image', models.ImageField(null=True, upload_to='')),
                ('Lien', models.CharField(max_length=520)),
            ],
        ),
    ]
