# Generated by Django 2.2.5 on 2020-04-13 17:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0047_partenairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accueil_page',
            name='Intro',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=100000),
        ),
    ]
