# Generated by Django 2.2.5 on 2020-04-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0048_auto_20200413_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='nos_partenaire',
            field=models.CharField(default='Nos clients et partenaires', max_length=300),
        ),
    ]
