# Generated by Django 2.2.5 on 2020-04-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0050_menu_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_bar',
            name='A_propos',
            field=models.CharField(blank=True, default='A_propos', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='menu_bar',
            name='Prestations',
            field=models.CharField(blank=True, default='prestations', max_length=80, null=True),
        ),
    ]
