# Generated by Django 2.2.5 on 2020-04-17 01:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0053_auto_20200415_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro_prestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Introduction', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
