# Generated by Django 2.2.5 on 2019-11-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=80)),
                ('pub', models.CharField(blank=True, default='M.Y.CHETOUANI', max_length=40, null=True)),
                ('Contenu', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('Photo', models.ImageField(upload_to='')),
                ('Date_de_pub', models.DateTimeField(null=True)),
                ('draft', models.BooleanField(default=False)),
                ('Domaine', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
