# Generated by Django 2.2.5 on 2019-11-25 22:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='Contenu',
            field=tinymce.models.HTMLField(),
        ),
    ]
