# Generated by Django 2.2.5 on 2019-11-25 23:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0002_auto_20191125_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='Contenu',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
