# Generated by Django 2.2.5 on 2020-03-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0004_auto_20191126_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='Domaine',
            new_name='Mot_Cle',
        ),
    ]
