# Generated by Django 2.2.5 on 2020-04-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0005_auto_20200327_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='pub',
            new_name='auteur',
        ),
    ]
